name: Go CI

on:
  push:
    branches: [ "build" ]
  pull_request:
    branches: [ "build" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: go mod tidy

    - name: Build
      run: go build ./...

    - name: Run Unit Tests with Coverage
      run: go test ./... -v -covermode=atomic -coverprofile=coverage.out

    - name: Show Coverage
      run: go tool cover -func=coverage.out

    - name: Upload coverage artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.out

