name: Recreate Test Branch

on:
  schedule:
    # Runs at 6:30 AM UTC every day
    - cron: '30 6 * * *'

jobs:
  recreate_test_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          # This is necessary to fetch all history and branches
          fetch-depth: 0

      - name: Recreate test branch if it doesn't exist
        # This step checks if the remote 'test' branch exists.
        # The '|| true' allows the command to fail without stopping the workflow,
        # which is expected if the branch doesn't exist.
        # The 'test' branch is created from 'main' and then pushed to the remote.
        run: |
          if git ls-remote --heads origin test | grep -q 'refs/heads/test'; then
            echo "The 'test' branch already exists. No action needed."
          else
            echo "The 'test' branch does not exist. Recreating it from 'main'."
            git branch test
            git push origin test
            echo "Successfully recreated the 'test' branch."
          fi
